version: '3.8'

services:
  app:
    image: wyssemdt/exercicedevops:latest
    container_name: student-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      APP_DB_HOST: 172.17.0.1
      APP_DB_USER: nodeapp
      APP_DB_PASSWORD: student12
      APP_DB_NAME: STUDENTS
      APP_PORT: 3000