version: '3.8'

services:
  app:
    build: .
    container_name: student-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      APP_DB_HOST: host.docker.internal
      APP_DB_USER: nodeapp
      APP_DB_PASSWORD: student12
      APP_DB_NAME: STUDENTS
      APP_PORT: 3000